(#4) Windows processes snapshot
ForNeVeR/ProcessDoctor pull request #17
Opened 2024-01-30 23:14 UTC by y0ung3r

**Should close #4**

**Changed:**
- `ProcessModel` has been renamed to `SystemProcess` (because `SystemProcess` will be the extension point for each operating system)
- Created a `WindowsProcess` (`SystemProcess` inheritor) model that encapsulates factories for creating a process from `WinAPI` structures and `WMI` objects
- Implemented `ProcessesSnapshot` class to get Windows processes snapshot
- Added `PInvoke` dependency for interaction with `WinAPI` (`PInvoke` is no longer maintained. In future, we should use [CsWin32](https://github.com/microsoft/CsWin32) when stable version is released)

**Screenshot:**

![image](https://github.com/ForNeVeR/ProcessDoctor/assets/55300023/089f4062-8766-40cd-a5ce-fa3ba0048696)

2024-01-31 23:03 UTC, ForNeVeR requested changes
Thanks! This is great. I have some small concerns, please address them, and this will be ready for merge. Thanks!

2024-01-31 23:03 UTC, ForNeVeR commented on ProcessDoctor.Backend.Windows/NT/Extensions/ProcessBasicInformationExtensions.cs
> +#endif
_(Minor)_ Generally, I'd say we are not interested in the 32-bit Windows target. Is it even supported on modern Windows versions? I suggest to just get rid of it.

2024-01-31 23:03 UTC, ForNeVeR commented on ProcessDoctor.Backend.Windows/NT/Extensions/ProcessHandleExtensions.cs
> +        var pointer = Marshal.AllocHGlobal(length);
Here you don't need to allocate the memory using `Marshal.AllocHGlobal`. You could just create a structure on the stack and pass its address to `NtQueryInformationProcess`, right?

2024-01-31 23:03 UTC, ForNeVeR commented on ProcessDoctor.Backend.Windows/NT/Extensions/UnicodeStringExtensions.cs
> +        return Encoding.Unicode.GetString(bytes);
Let's try something like this instead:
```
if (unmanagedString.Length % 2 != 0) {
  // malformed UTF-16 string
  throw new CorruptedProcessHandleException();
}

var span = new Span<char>(unmanagedString.Buffer, unmanagedString.Length / 2);
return new string(span);
```

This should be more efficient.

2024-01-31 23:03 UTC, ForNeVeR commented on ProcessDoctor.Backend.Windows/ProcessMemoryReader.cs
> +    }
Here I'd prefer the following implementation:
```csharp
private unsafe bool TryRead(IntPtr address, Span<byte> resultArray)
{
    fixed (byte* data = resultArray)
    {
        var isSuccess = Kernel32.ReadProcessMemory(
            _processHandle,
            address,
            (IntPtr)data,
            (nuint)resultArray.Length,
            out var totalLength);

        return isSuccess && (nuint)resultArray.Length == totalLength;
    }
}
```

Note how it accepts a managed array and thus no longer requires `AllocHGlobal` and all that.

You'd be able to call it like this:
```csharp
public T? ReadStructure<T>(IntPtr address)
    where T : unmanaged
{
    T instance = default;
    if (!TryRead(address, MemoryMarshal.AsBytes(MemoryMarshal.CreateSpan(ref instance, 1))))
    {
        return null;
    }

    return instance;
}
```

(I didn't test this approach, but I think it should work, heh)

2024-02-01 08:12 UTC, y0ung3r commented on ProcessDoctor.Backend.Windows/NT/RTL_USER_PROCESS_PARAMETERS.cs
> +    private fixed int Reserved2[20];
Honestly, I don't know how to write a fixed `PVOID` array any other way. Maybe you have some ideas?

2024-02-01 08:19 UTC, y0ung3r commented on ProcessDoctor.Backend.Windows/NT/Extensions/ProcessHandleExtensions.cs
> +        var pointer = Marshal.AllocHGlobal(length);
That's right

2024-02-01 08:21 UTC, y0ung3r commented on ProcessDoctor.Backend.Windows/ProcessMemoryReader.cs
> +    }
I got rid of `ProcessMemoryReader` and put all that code in the extension methods

2024-02-01 09:29 UTC, y0ung3r commented on ProcessDoctor.Backend.Windows/NT/RTL_USER_PROCESS_PARAMETERS.cs
> +    private fixed int Reserved2[20];
Replaced `int` with `long` and returned the standard array size. It seems to be working 😁

2024-02-01 22:47 UTC, ForNeVeR approved these changes
Thanks for contribution!

2024-02-01 22:47 UTC, merged